language: python
python:
  - "3.7"
env:
  matrix:
  - TOXENV=py37
  - TOXENV=pep8

install:
  - travis_retry pip install tox
  - pip install codecov
script:
  - tox
  - test -d .tox/$TOXENV/log && cat .tox/$TOXENV/log/*.log || true
cache:
  directories:
    - $HOME/.cache/pip
after_success:
  - codecov